import Head from 'next/head';
import Link from 'next/link';
import { useContext } from 'react';
import { storeContext } from '../store/store';

const Layout = ({ title, children }) => {
  const { state } = useContext(storeContext);

  return (
    <>
      <Head>
        <title>{title ? `${title} - Amazona` : `Amazona`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 items-center px-4 justify-between shadow-md">
            <Link href="/" className="text-lg font-bold">
              Amazona
            </Link>
            <div>
              <Link href="/cart" className="p-2">
                Cart
                {state.cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
              </Link>
              <Link href="/login" className="p-2">
                Login
              </Link>
            </div>
          </nav>
        </header>

        <main className="container">{children}</main>

        <footer className="flex justify-center items-center shadow-inner">
          <p> copyright 2022 Amazona</p>
        </footer>
      </div>
    </>
  );
};

export default Layout;
